POST http://localhost:8082/api/v1/notifications/email
Content-Type: application/json

{
  "to": "other@example.com",
  "subject": "Bem-vindo!",
  "body": "Olá Rafhael, sua conta foi criada com sucesso."
}

###

GET http://localhost:8082/api/v1/notifications/email
Content-Type: application/json

###

@id = EM2MWFRDQETN3GAAWDA4Y77PCM

GET http://localhost:8082/api/v1/notifications/email/{{id}}
Content-Type: application/json
